.idea/misc.xml
README.md

per Lexi's notes on our proposal doc, I updated the readme (again) but this time did it on a new branch and have now pushed it to main --in an attempt to get listed as a contributor.

adding MH as contributor to repo

---

README.md

hope this works. I want to be a contributor

trying again but this time from the terminal

---

next-chapter/src/main/java/org/launchcode/nextchapter/models/AbstractEntity.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/User.java
next-chapter/src/main/resources/static/styles.css
next-chapter/src/main/resources/templates/index.html

User and Club models have been refactored to extend an AbstractEntity with contains id and displayName

Abstract entity

---

next-chapter/build.gradle
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/User.java
next-chapter/src/main/resources/templates/clubs/create.html
next-chapter/src/main/resources/templates/index.html
next-chapter/src/main/resources/templates/users/create.html

I added password fields for user and club, but much more work is required to actually implement these. I think I will have time this weekend. For now, you will see the new columns show up in MySQL.

Add password field

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/AuthenticationController.java
next-chapter/src/main/java/org/launchcode/nextchapter/data/UserRepository.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/User.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/dto/LoginFormDTO.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/dto/RegisterFormDTO.java
next-chapter/src/main/resources/templates/fragments.html
next-chapter/src/main/resources/templates/index.html
next-chapter/src/main/resources/templates/login.html
next-chapter/src/main/resources/templates/register.html

I added an authentication controller, like we did for coding events in week 19(?) of Java. I made "register" and "login" pages, which you can access at the bottom of the home page. I redirected "create user" to the registration page.

New login page

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/AuthenticationController.java
next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/java/org/launchcode/nextchapter/data/ClubRepository.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/dto/CreateClubFormDTO.java
next-chapter/src/main/resources/templates/clubs/create.html
next-chapter/src/main/resources/templates/clubs/detail.html
next-chapter/src/main/resources/templates/index.html

This update includes password functionality for the club creation.

Club admin

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/resources/templates/clubs/detail.html
next-chapter/src/main/resources/templates/clubs/leave.html

I updated the club details page to only list club members if the current session user is a member of that club. If they are not a member of that club, then they see a link to join the club. If they are a member of that club, they will also see a link that lets them leave the club. The "leave" page also gives them an option to not leave and just return to the detail page.

Club info conditional display

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java

This branch fixes a few small issues. It fixes the redirect when someone joins a club (the bug that Molly found). It also adds the member id of the club creator as the "adminId", and it add the club creator as a member automatically.

Blog post redirect bug

---

.idea/shelf/Uncommitted_changes_before_Checkout_at_2_1_24,_10_07 PM_[Changes]/shelved.patch
.idea/shelf/Uncommitted_changes_before_Checkout_at_2_1_24,_10_07 PM_[Changes]1/shelved.patch
.idea/shelf/Uncommitted_changes_before_Checkout_at_2_1_24__10_07PM__Changes_.xml
.idea/shelf/Uncommitted_changes_before_Checkout_at_2_1_24__10_07PM__Changes_1.xml
next-chapter/src/main/java/org/launchcode/nextchapter/controllers/BlogController.java
next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Blog.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Member.java
next-chapter/src/main/resources/templates/blog/create.html
next-chapter/src/main/resources/templates/clubs/detail.html

The redirect to the details page is working perfectly, thanks Bekah. Looks like this branch "Can’t automatically merge" so I'm uncertain where the conflict is arising and how to best merge this branch.... let's figure it out together if it's not immediately clear.

Add functioning blog to club page

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/SearchController.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java
next-chapter/src/main/resources/templates/clubs/detail.html
next-chapter/src/main/resources/templates/search.html

Molly, this is what I came up with to get coverId to update with the api search. I don't think I changed your branch, but made all my changes in the -bekah version of your branch.

used book image result to update club's coverId

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/SearchController.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java
next-chapter/src/main/resources/templates/clubs/detail.html
next-chapter/src/main/resources/templates/search.html

Now the member will be asked to type in the book title within the "cover ID selection" form, so that we can ensure the title matches the coverID -- and so the activeBook can be updated.
This is a clumsy work-around -- the more elegant fix would be to make activeBook its own model, and populate the title directly from the API results. However this will entail a lot of code updates, so for now I think it's best to stick with this.
I see there is a merge conflict so I am going to create this request and then see what pops up as the conflict.

"Add coverID to club (Bekah)" AND "Add book title to search return"

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/AuthenticationController.java
next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/dto/AdminFormDTO.java
next-chapter/src/main/resources/static/styles.css
next-chapter/src/main/resources/templates/clubs/admin.html
next-chapter/src/main/resources/templates/clubs/detail.html

This is the club administration page. There is a link at the bottom of the club detail page that takes you to a form. The admin password is required to make any changes. The admin can update the club name, delete any members, delete any blog posts, or delete the entire club.

Club admin 2

---

.idea/.name
.idea/compiler.xml
.idea/jarRepositories.xml
next-chapter/src/main/resources/static/styles.css
next-chapter/src/main/resources/templates/clubs/detail.html
next-chapter/src/main/resources/templates/fragments.html
next-chapter/src/main/resources/templates/index.html
next-chapter/src/main/resources/templates/search.html

Please see commits for details on all changed features.

Add logo (and other styling changes)

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/resources/templates/clubs/admin.html

This is a small update to double-check a new club name against the existing clubs in the repository. If another club exists with that name, the admin page is returned and an error message is displayed.

club admin page checks if club name already exists, and if so it displays an error message

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Club.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/dto/CreateClubFormDTO.java
next-chapter/src/main/resources/templates/clubs/create.html
next-chapter/src/main/resources/templates/clubs/detail.html

Added description field to club and updated DTO, and templates for create and details.
Noted a bug where PostMapping for clubs/create.html directed to clubs/index -- changed it to now direct to clubs/details.html

Add description to club + bugfix

---

next-chapter/src/main/java/org/launchcode/nextchapter/AuthenticationFilter.java
next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/resources/static/styles.css
next-chapter/src/main/resources/templates/clubs/index.html
next-chapter/src/main/resources/templates/fragments.html

Club index page displays all club names and their current book. club names are clickable buttons. Buttons navigate to the club detail page if user is logged in, and buttons do nothing if user is not logged in.

Club index

---

next-chapter/src/main/resources/templates/blog/create.html
next-chapter/src/main/resources/templates/blog/index.html
next-chapter/src/main/resources/templates/clubs/admin.html
next-chapter/src/main/resources/templates/clubs/create.html
next-chapter/src/main/resources/templates/clubs/detail.html
next-chapter/src/main/resources/templates/clubs/index.html
next-chapter/src/main/resources/templates/clubs/join.html
next-chapter/src/main/resources/templates/clubs/leave.html
next-chapter/src/main/resources/templates/index.html
next-chapter/src/main/resources/templates/login.html
next-chapter/src/main/resources/templates/members/create.html
next-chapter/src/main/resources/templates/members/index.html
next-chapter/src/main/resources/templates/register.html
next-chapter/src/main/resources/templates/search.html
next-chapter/src/main/resources/templates/searchbar.html

This is a small update to wrap fragments. I kept getting a warning that unwrapped fragments will not be supported by future versions of thymeleaf. Now fragments comply.

wrapped fragments to comply with future versions of thymeleaf

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/BlogController.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/Blog.java
next-chapter/src/main/resources/templates/blog/create.html

Errors now show properly on blog/create.html when trying to submit an incomplete blog post.

Blog validation

---

next-chapter/src/main/resources/templates/clubs/detail.html

if conditional and alternate image added to detail.html at line 52-53

"image not available" added to club/detail.html when coverId=null

---

next-chapter/src/main/java/org/launchcode/nextchapter/controllers/ClubController.java
next-chapter/src/main/java/org/launchcode/nextchapter/models/dto/AdminUpdatePasswordDTO.java
next-chapter/src/main/resources/templates/clubs/update-password.html

This update posts an error message if the new password is the same as the current password. I also added a button to go back to the club detail page.

updates to change-club-password page
